spring:
  application:
    name: StorageService
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uris:
            sso: ${JWK_SSO_URL:http://localhost:8080/realms/iam_service/protocol/openid-connect/certs}
            internal: ${JWK_INTERNAL_URL:http://localhost:8085/api/v1/auth/certificate/.well-known/jwks.json}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/StorageService
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
storage:
  upload_uri_pattern: yyyy-MMMM\\dd
  upload_path: file
  download-base-url: http://localhost:${server.port}/api/v1
server:
  port: 8086
debug: true
logging:
  level:
    org.springframework.security: trace
app:
  iam:
    internal-url: http://localhost:8085
keycloak:
  server-url: http://localhost:8080