spring:
  application:
    name: IAMService2
  datasource:
    url: jdbc:postgresql://localhost:5432/IAM_Service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uris:
            sso: ${JWK_SSO_URL:http://localhost:8080/realms/iam_service/protocol/openid-connect/certs}
            internal: ${JWK_INTERNAL_URL:http://localhost:8085/api/v1/auth/certificate/.well-known/jwks.json}
default-idp:
keycloak:
  client_id: client
  client_secret: L4cQEfVjcmoA4bzujcpwG23iYmP4iZhn
  server_url: http://localhost:8080
  realm: "iam_service"
  username: admin@mail.com
  password: 123456

logging:
  level:
    org.springframework.security: trace
debug: true
server:
  port: 8085
service:
  mail:
    from: hellohoangson@gmail.com
    sendgrid:
      apiKey: "000"
application:
  token:
    verify_account:
      live-time-secs: 1800
springdoc:
  show-actuator: true
app:
  iam:
    internal-url: http://localhost:8085